### ISSUE TITLE
this fork works currently

### ISSUE THREAD

**Issue by hkhere** [lukasgit/flutter_contacts#345]
[flutter_contacts](https://github.com/hkhere/flutter_contacts)

**Comment by hkhere** [comment]
if anyone wants to use the one i mentioned above, replace the `contact_service: a.b.c` entry in the `pubspec.yaml` with the following one:
```yaml
  contacts_service:
    git:
      url: https://github.com/hkhere/flutter_contacts.git
      ref: master
```
